[_]
schema-version = "0.2"

[[io.buildpacks.group]]
id = "heroku/nodejs"

[[io.buildpacks.group]]
id = "heroku/static-web-server"

[com.heroku.build.labs]
build_config_vars = true

[com.heroku.static-web-server]
root = "dist"
index = "index.html"

[com.heroku.static-web-server.errors.404]
file_path = "index.html"
status = 200
path_exclusions = ["/assets/*"]

[com.heroku.static-web-server.runtime_config]
enabled = false

[com.heroku.static-web-server.headers."/"]
Cache-Control = "no-cache"

[com.heroku.static-web-server.headers."/*.html"]
Cache-Control = "no-cache"

[com.heroku.static-web-server.headers."/assets/*"]
Cache-Control = "public, max-age=31536000, immutable"
